### ISSUE TITLE
Monkey Paw and Bones

### ISSUE THREAD

**Issue by Kendall924** [dot2JC/GIMP#15]
![image](https://user-images.githubusercontent.com/93501180/144908655-52e7d6d7-10f5-4c84-bf12-3976cde906bb.png)
may be worth mentioning to kill a monkey while in Karamja for the monkey paw and bones. I'm sure it mentions the bones earlier if I remember but you need the paw for rag and bone man anyway.

**Comment by dot2JC** [comment]
While it is intended to deviate from the guide upon questing, it does make sense to at least mention the paw for R&BM2, so I went ahead and added the bones too.
