### ISSUE TITLE
Maple Logs for Birdhouses

### ISSUE THREAD

**Issue by Kendall924** [dot2JC/GIMP#16]
Says to Fletch all maple logs and leave some for birdhouses and then later in the guide it says to keep a certain amount. maybe move the amount kept up to that point to remove confusion.

![image](https://user-images.githubusercontent.com/93501180/147117596-060e5ba7-9c3a-47ca-98d8-e22325c45acb.png)

**Comment by dot2JC** [comment]
Fixed in commit a51f3ec
