### ISSUE TITLE
Redberries

### ISSUE THREAD

**Issue by Kendall924** [dot2JC/GIMP#5]
![image](https://user-images.githubusercontent.com/93501180/139714511-b4035d0a-a8ac-4248-b745-d15148f3b5bd.png)

so it says redberries are available for purchase at port Seram but we gathered some earlier, do we not use those? makes it sound like you save them for something

**Comment by dot2JC** [comment]
Fixed in https://github.com/dot2JC/GIMP/commit/9d977f7a9fc390851799084acab1a4d3578b1bdb
