### ISSUE TITLE
TDIL

### ISSUE THREAD

**Issue by Kendall924** [dot2JC/GIMP#6]
1) count check in the lumby grave yard can tele you once and only once to the stronghold of security provided you haven't been there yet.
[10:19 AM]
2) if you tell the people your a bandit at the shanty pass and the deny to pay your bail twice they will tele you to port Sarim jail and you can pick the lock whiteout a pick and leave

**Comment by dot2JC** [comment]
Fixed in commit https://github.com/dot2JC/GIMP/commit/106f5710baba69f19cf7a6adc612f14ba93f9e01
