### ISSUE TITLE
Essence Mine Step Unclear

### ISSUE THREAD

**Issue by Kendall924** [dot2JC/GIMP#7]
![image](https://user-images.githubusercontent.com/93501180/140376540-3058a11e-f064-470a-be31-09b02de0add5.png)

During the step when you visit the essence mine for enter the abyss, mention Aubury for clarity on where to go and how far into the mini quest you do it.

**Comment by dot2JC** [comment]
Fixed in commit https://github.com/dot2JC/GIMP/commit/01429e748038cc9c579d9bf72af370fa764d6d92
