### ISSUE TITLE
NPC Highlighter 

### ISSUE THREAD

**Issue by Kendall924** [dot2JC/GIMP#8]
Add kitten to npc highlighter

**Comment by dot2JC** [comment]
Will need to validate and see how awful this looks ingame because NPC highlighter highlights all entities with the same name.

**Comment by Kendall924** [comment]
its pretty nice tbh, I like it. it could be up to each individual. but there isn't enough kittens around to make it a cluster and even if there is allot of kittens the odds of it throwing you off isn't much. example here while fishing. there are a decent amount of kittens but they stack and yours is the only one that even appears when hovered over. I find it quicker to find your kitten even in that scenario aw well. plus them bastards are small and blend in sometimes when not highlighted.
![image](https://user-images.githubusercontent.com/93501180/141883909-1844c566-39ce-4b25-b8ee-f25df1a30701.png)

**Comment by Kendall924** [comment]
Just another prospective I wanted to add since it does occur often. in this picture there are 3 kittens and other pets. you can see all three kittens through the other pets which would be harder to do normally. secondly even though there are 3 kittens yours being the only your mouse activates on is a plus.
![image](https://user-images.githubusercontent.com/93501180/142083017-fe2c02f1-d6fa-4454-a102-7b09131fd5ec.png)

**Comment by dot2JC** [comment]
Seems to not really be an issue, so we're pushing this live. The NPC highlighter pastebin will have Kitten appended.
