### ISSUE TITLE
The Feud 

### ISSUE THREAD

**Issue by Kendall924** [dot2JC/GIMP#9]
![image](https://user-images.githubusercontent.com/93501180/140589527-da411cdc-3f08-4bd8-b4dc-5fc272a01b21.png)

Misleading, makes it sound like you start the quest in the desert, not right through the gate.

**Comment by dot2JC** [comment]
Fixed in commit https://github.com/dot2JC/GIMP/commit/01429e748038cc9c579d9bf72af370fa764d6d92
